<project xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>Yune</groupId>
  <artifactId>Yune</artifactId>
  <version>0.9.4</version>
  <name>Yune</name>
  <description>A Universal Fire Emblem Randomizer</description>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <resources>
      <resource>
        <directory>res</directory>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>26</source>
          <target>26</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
  
  <dependencies>
  	<dependency>
  	  <groupId>com.google.code.gson</groupId>
  	  <artifactId>gson</artifactId>
  	  <version>2.11.0</version>
  	</dependency>
  </dependencies>
  
  <profiles>
    <profile>
        <id>swt-windows</id>
        <activation>
            <os>
                <family>windows</family>
            </os>
        </activation>
        <dependencies>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.swt.win32.win32.x86_64</artifactId>
                <version>3.134.0</version>
            </dependency>
        </dependencies>
    </profile>

    <profile>
        <id>swt-linux</id>
        <activation>
            <os>
                <name>linux</name>
            </os>
        </activation>
        <dependencies>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.swt.gtk.linux.x86_64</artifactId>
                <version>3.134.0</version>
            </dependency>
        </dependencies>
    </profile>

    <profile>
        <id>swt-mac</id>
        <activation>
            <os>
                <family>mac</family>
            </os>
        </activation>
        <dependencies>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.swt.cocoa.macosx.aarch64</artifactId>
                <version>3.134.0</version>
            </dependency>
        </dependencies>
    </profile>
  </profiles>
</project>